"""followers

Revision ID: 669b4a01631e
Revises: c34d0c698bd1
Create Date: 2022-03-14 07:54:57.935118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669b4a01631e'
down_revision = 'c34d0c698bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
